'use strict'; // code generated by pbf v3.2.1

// CityRoadChunk ========================================

export const CityRoadChunk = {};

CityRoadChunk.read = function (pbf, end) {
    return pbf.readFields(CityRoadChunk._readField, {schema_version: 0, city_key: "", dataset_revision: "", chunk_index: 0, chunk_count: 0, detail_level: 0, roads: []}, end);
};
CityRoadChunk._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.schema_version = pbf.readVarint();
    else if (tag === 2) obj.city_key = pbf.readString();
    else if (tag === 3) obj.dataset_revision = pbf.readString();
    else if (tag === 4) obj.chunk_index = pbf.readVarint();
    else if (tag === 5) obj.chunk_count = pbf.readVarint();
    else if (tag === 6) obj.detail_level = pbf.readVarint();
    else if (tag === 7) obj.roads.push(RoadPolyline.read(pbf, pbf.readVarint() + pbf.pos));
};
CityRoadChunk.write = function (obj, pbf) {
    if (obj.schema_version) pbf.writeVarintField(1, obj.schema_version);
    if (obj.city_key) pbf.writeStringField(2, obj.city_key);
    if (obj.dataset_revision) pbf.writeStringField(3, obj.dataset_revision);
    if (obj.chunk_index) pbf.writeVarintField(4, obj.chunk_index);
    if (obj.chunk_count) pbf.writeVarintField(5, obj.chunk_count);
    if (obj.detail_level) pbf.writeVarintField(6, obj.detail_level);
    if (obj.roads) for (var i = 0; i < obj.roads.length; i++) pbf.writeMessage(7, RoadPolyline.write, obj.roads[i]);
};

// RoadPolyline ========================================

export const RoadPolyline = {};

RoadPolyline.read = function (pbf, end) {
    return pbf.readFields(RoadPolyline._readField, {osm_way_id: "", highway: "", first_lon_e7: 0, first_lat_e7: 0, coordinate_deltas_e7: [], fragment_index: 0, bridge: false, tunnel: false, layer: 0}, end);
};
RoadPolyline._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.osm_way_id = pbf.readString();
    else if (tag === 2) obj.highway = pbf.readString();
    else if (tag === 3) obj.first_lon_e7 = pbf.readSVarint();
    else if (tag === 4) obj.first_lat_e7 = pbf.readSVarint();
    else if (tag === 5) pbf.readPackedSVarint(obj.coordinate_deltas_e7);
    else if (tag === 6) obj.fragment_index = pbf.readVarint();
    else if (tag === 7) obj.bridge = pbf.readBoolean();
    else if (tag === 8) obj.tunnel = pbf.readBoolean();
    else if (tag === 9) obj.layer = pbf.readSVarint();
};
RoadPolyline.write = function (obj, pbf) {
    if (obj.osm_way_id) pbf.writeStringField(1, obj.osm_way_id);
    if (obj.highway) pbf.writeStringField(2, obj.highway);
    if (obj.first_lon_e7) pbf.writeSVarintField(3, obj.first_lon_e7);
    if (obj.first_lat_e7) pbf.writeSVarintField(4, obj.first_lat_e7);
    if (obj.coordinate_deltas_e7) pbf.writePackedSVarint(5, obj.coordinate_deltas_e7);
    if (obj.fragment_index) pbf.writeVarintField(6, obj.fragment_index);
    if (obj.bridge) pbf.writeBooleanField(7, obj.bridge);
    if (obj.tunnel) pbf.writeBooleanField(8, obj.tunnel);
    if (obj.layer) pbf.writeSVarintField(9, obj.layer);
};
